#!/bin/bash

# debug
# set -x

# check needed vars
if [[ -z $OPENSHIFT_REPO_DIR ]]; then
    echo "Error: OPENSHIFT_REPO_DIR not defined"
    return 1
fi

if [[ -z $OPENSHIFT_DATA_DIR ]]; then
    echo "Error: OPENSHIFT_DATA_DIR not defined"
    return 1
fi

if [[ -z $OPENSHIFT_TMP_DIR ]]; then
    echo "Error: OPENSHIFT_TMP_DIR not defined"
    return 1
fi

if [[ -z $OPENSHIFT_LOG_DIR ]]; then
    echo "Error: OPENSHIFT_LOG_DIR not defined"
    return 1
fi

# Racket Version to download and install
VERSION="5.2.1"
RACKET_LAUNCH_PARAMS=""
RACKET_INIT_FILE="${OPENSHIFT_REPO_DIR}conf/racketrc"

# validate version
if [ "$VERSION" \< "5.2.1" ]; then
    echo "Error: version $VERSION not supported, use version 5.2.1 or higher"
    return 1
fi

LOG_FILE="${OPENSHIFT_LOG_DIR}system.out"
RACKET_COMMAND="${OPENSHIFT_DATA_DIR}/racket/bin/racket"

return 0